### ISSUE TITLE
Bijkomende vragen

### ISSUE THREAD

**Issue by MarijkeThoonen** [MarijkeThoonen/Fallopia#4]
- is het ok om log(eindopp/beginopp) nog eens te delen om de relatieve jaarlijkse uitbreiding te bekomen? Precies niet veel verschil
- Ik zie in dat delen door de eindoppervlakte fout was. De uitbreiding ten opzichte van de nulsituatie in 2018 moet bepaald worden. Die variabele geeft de effectgrootte van het beheer in de voorbije drie jaar. 
- Afwijking van het gemiddelde zoals in het paper is misschien typische voor variabelen die de neiging hebben te schommelen rond een gemiddelde, terwijl de duinzekdnoop gaat uitbreiden, misschien ook iets meer of minder afhankelijk van het weer.
- Wil je de verwoording van de analyse in het rapport ook eens nalezen?
- Dankje!

**Comment by hansvancalster** [comment]
> * is het ok om log(eindopp/beginopp) nog eens te delen om de relatieve jaarlijkse uitbreiding te bekomen? Precies niet veel verschil

Er zijn maar een beperkt aantal gevallen waar het verschil 3 jaar is ipv 4 jaar. Het zal inderdaad niet veel uitmaken, maar je mag dit doen.

**Comment by MarijkeThoonen** [comment]
Reden is om een variabele te geven waar een beheerder zich iets bij kan voorstellen.
